import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "News Homepage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/favicon-32x32.png" />
      </head>
      <body
      >
        {children}
      </body>
    </html>
  );
}
